// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

namespace osu.Framework.Graphics.Spirv
{
    // https://github.com/KhronosGroup/SPIRV-Headers/blob/01e0577914a75a2569c846778c2f93aa8e6feddd/include/spirv/1.0/spirv.h#L325
    public enum SpvDecoration
    {
        SpvDecorationRelaxedPrecision = 0,
        SpvDecorationSpecId = 1,
        SpvDecorationBlock = 2,
        SpvDecorationBufferBlock = 3,
        SpvDecorationRowMajor = 4,
        SpvDecorationColMajor = 5,
        SpvDecorationArrayStride = 6,
        SpvDecorationMatrixStride = 7,
        SpvDecorationGLSLShared = 8,
        SpvDecorationGLSLPacked = 9,
        SpvDecorationCPacked = 10,
        SpvDecorationBuiltIn = 11,
        SpvDecorationNoPerspective = 13,
        SpvDecorationFlat = 14,
        SpvDecorationPatch = 15,
        SpvDecorationCentroid = 16,
        SpvDecorationSample = 17,
        SpvDecorationInvariant = 18,
        SpvDecorationRestrict = 19,
        SpvDecorationAliased = 20,
        SpvDecorationVolatile = 21,
        SpvDecorationConstant = 22,
        SpvDecorationCoherent = 23,
        SpvDecorationNonWritable = 24,
        SpvDecorationNonReadable = 25,
        SpvDecorationUniform = 26,
        SpvDecorationSaturatedConversion = 28,
        SpvDecorationStream = 29,
        SpvDecorationLocation = 30,
        SpvDecorationComponent = 31,
        SpvDecorationIndex = 32,
        SpvDecorationBinding = 33,
        SpvDecorationDescriptorSet = 34,
        SpvDecorationOffset = 35,
        SpvDecorationXfbBuffer = 36,
        SpvDecorationXfbStride = 37,
        SpvDecorationFuncParamAttr = 38,
        SpvDecorationFPRoundingMode = 39,
        SpvDecorationFPFastMathMode = 40,
        SpvDecorationLinkageAttributes = 41,
        SpvDecorationNoContraction = 42,
        SpvDecorationInputAttachmentIndex = 43,
        SpvDecorationAlignment = 44,
        SpvDecorationExplicitInterpAMD = 4999,
        SpvDecorationOverrideCoverageNV = 5248,
        SpvDecorationPassthroughNV = 5250,
        SpvDecorationViewportRelativeNV = 5252,
        SpvDecorationSecondaryViewportRelativeNV = 5256,
        SpvDecorationHlslCounterBufferGOOGLE = 5634,
        SpvDecorationHlslSemanticGOOGLE = 5635,
        SpvDecorationMax = 0x7fffffff,
    }
}
