name: Build FFmpeg
on: workflow_dispatch

jobs:
  build-osx:
    name: Build OSX
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/setup-nasm@v1

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/osx/fetch_and_build.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: osx-${{ matrix.arch }}
          path: build-${{ matrix.arch }}

  combine-osx:
    name: Combine OSX libs
    runs-on: macos-latest
    needs: build-osx
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: osx-x86_64
          path: osx-x86_64
      - uses: actions/download-artifact@v3
        with:
          name: osx-arm64
          path: osx-arm64

      - name: Combine
        run: osu.Framework.NativeLibs/scripts/ffmpeg/osx/combine_universal.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: osx
          path: artifacts

  build-win:
    name: Build Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make nasm gcc mingw-w64

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/win/fetch_and_build.sh
        env:
          arch: ${{ matrix.arch }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-${{ matrix.arch }}
          path: build-${{ matrix.arch }}

  build-win-arm64:
    name: Build Windows (arm64)
    runs-on: ubuntu-latest
    container:
      image: mstorsjo/llvm-mingw:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/win/fetch_and_build.sh
        env:
          arch: arm64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win-arm64
          path: build-arm64

  build-linux:
    name: Build Linux (x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ilammy/setup-nasm@v1

      - name: Build
        run: osu.Framework.NativeLibs/scripts/ffmpeg/linux/fetch_and_build.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: build-x64

  make-pr:
    name: Create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: osx
          path: osu.Framework.NativeLibs/runtimes/osx/native
      - uses: actions/download-artifact@v3
        with:
          name: linux-x64
          path: osu.Framework.NativeLibs/runtimes/linux-x64/native
      - uses: actions/download-artifact@v3
        with:
          name: win-arm64
          path: osu.Framework.NativeLibs/runtimes/win-arm64/native
      - uses: actions/download-artifact@v3
        with:
          name: win-x64
          path: osu.Framework.NativeLibs/runtimes/win-x64/native
      - uses: actions/download-artifact@v3
        with:
          name: win-x86
          path: osu.Framework.NativeLibs/runtimes/win-x86/native

      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: Update FFmpeg binaries
        title: Update FFmpeg binaries
        body: This PR has been auto-generated to update the FFmpeg binaries.
        branch: update-ffmpeg-binaries
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
